# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9a22999fa678ba3684a4d00a73a55836c5ebcd5bcd106b0aa8f212df0b60ef044b94eb9bc13590489db076d8d7a022eba54f807457598fbf27ddef8abad2d36

test:
  secret_key_base: cd1b604b5f32f19225de067ef21d6e802e7336701ef70cebc951f9f2f1c8d8f5a19efbc1e21a1432bb241d1a438bdd85c9539f2feea42bbb46d192c88a01ff3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
